### ISSUE TITLE
Messages

### ISSUE THREAD

**Issue by willypro7** [TheAxiome/discord_ticket_maker#1]
Hi i wanna know how to change the message the bot sends.

it says Replace "message" with your message value but when i change message the bot crashes

**Comment by TheAxiome** [comment]
Hello @willyreh I will be adding that as an update today, also replacing the "message" value means the value for messages set in an message event

**Comment by TheAxiome** [comment]
Update to the latest version of the package, i have added the command!

**Comment by willypro7** [comment]
Ok! Thannx! My friend telled me
